services:
  mpi-master:
    image: 192.168.10.3:5000/mpi-test:latest
    user: root
    deploy:
      replicas: 1
    networks:
      - mpi-net
  mpi-worker:
    image: 192.168.10.3:5000/mpi-test:latest 
    user: root
    deploy:
      replicas: 2
    networks:
      - mpi-net

networks:
  mpi-net:
    driver: overlay
